[project]
authors = [
    { email = "theo.remon@zextras.fr", name = "Théo Remon" }
]
description = "API client for Zextras Admin Plus"
name = "zap-client"
license = { text = 'GPL-3.0-or-later' }
readme = "README.md"
requires-python = ">= 3.10"
version = "0.1.0"
